[[language]]
name = "rust"

[language-server.rust-analyzer.config]
check.command = "clippy"

[[language]]
name = "python"
language-servers = ["ruff", "pylsp"]
auto-format = true

[language-server.ruff]
command = "ruff-lsp"
