[font]
size = 12.0

[font.normal]
family = "MesloLGS NF"

[keyboard]
bindings = [{ key = "Space", mods = "Control", action = "ToggleViMode" }]

[env]
TERM = "xterm-256color"

[general]
import = ["~/.config/alacritty/themes/themes/one_dark.toml"]
